version: '2.2'

services:
  network-service:
    image: busybox
    command: sleep infinity
    init: true
  url-shortener:
    build: .
    image: url-shortener
    environment:
      - PORT=8080
    volumes:
      - urls:/data
    network_mode: service:network-service

volumes:
  urls:
